version: "3.9"
services:
  sportfin:
    container_name: sportfin-help
    stdin_open: true
    tty: true
    build: .
    volumes:
      - type: bind
        source: ./
        target: /code
    ports: 
      - 80:80
    env_file:
      - .env
  db:
    image: postgres:12-alpine
    container_name: sportfin-help-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
