name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Dokku Deploy action
        uses: dokku/github-action@master

        with:
           dokku_repo: 'ssh://dokku@18.135.196.165:22/basicdjango'
           ssh_key: ${{ secrets.SSH_KEY }}
           deploy_branch: 'basic-config'

