name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Dokku
        run: |
          git remote add dokku dokku@ec2-3-10-211-137.eu-west-2.compute.amazonaws.com:help-center
          git push dokku main
